// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacf96sbeIihCzVBZdVO9OkjaKAtjNpgo',
    appId: '1:325059982636:android:b0e27dc8d9f95bc8ed2889',
    messagingSenderId: '325059982636',
    projectId: 'presence-99d0d',
    storageBucket: 'presence-99d0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfGMNfseoBxX0slU6HpgUlT_NeNMIid3U',
    appId: '1:325059982636:ios:e696f8f97f8c6e00ed2889',
    messagingSenderId: '325059982636',
    projectId: 'presence-99d0d',
    storageBucket: 'presence-99d0d.appspot.com',
    iosClientId: '325059982636-jog2u8chgod6me0t5lkqt8q9olqtpr76.apps.googleusercontent.com',
    iosBundleId: 'com.bagasproject.presence',
  );
}
